name: AWS Destroy
on: 
  workflow_dispatch:
jobs:
  DestroyAWS:
    environment: 
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v3
        - name: Setup AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: us-west-2
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            role-session-name: github-action

        - name: Setting stage and stack name
          run: |
            echo "STAGE=${{ github.ref_name }}" 
            PROJECT_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1' | sed -e 's/ //g')
            echo "PROJECT_NAME=${PROJECT_NAME}"
            echo "STACK_NAME=${PROJECT_NAME}Stack${{github.ref_name}}"

            echo "STACK_NAME=${PROJECT_NAME}Stack${{github.ref_name}}" >> $GITHUB_ENV
            echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
    
        - name: Installing Dependencies to Destroy
          run: |
            cd iac
            npm install -g aws-cdk
            npm i
        - name: Installing Dependencies to BattleSnake
          run: |
            npm i
            npm run build
        - name: Setup envs
          run: |
            echo AWS_REGION=us-west-2 >> $GITHUB_ENV
            echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
            echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV

            echo ${{ env.AWS_REGION }}
            echo ${{ env.AWS_ACCOUNT_ID }}
            echo ${{ env.STACK_NAME }}
            echo ${{ env.GITHUB_REF_NAME }}

        - name: Destroy CDK
          run: |
            cd iac
            cdk destroy --force
       
    